### PR TITLE
Html remodeling

### PR DESCRIPTION
**Pull request by jasonmeeks**
yippeeeee changed the html format

### CODE REVIEW

**Comment by Mester** [comment]
Looks pretty good! I say merge it

**Comment by an00bhav** [comment]
This is good, there are some minor changes we can do here. 
@jasonmeeks Is it somehow possible to get the results center justified?

screen shot 2016-07-03 at 6 21 27 pm

Also, Can we get rid of the borders? And I think we need to change the color of the font? Thoughts?

**Comment by bdauer** [comment]
I think we should keep the border but increase the margin between the input box and the results table. Agree on centering. 

Also noticing that we're pulling in that dash sometimes after the artist name.

Thinking, for the end user, might be better to use a standard format for the artist and song name like <artist> / <song> or <artist> -- <song> instead of as a list. But that would run into the issue of getting too long on one line. In any event these are small changes that can always happen later.

**Comment by an00bhav** [comment]
@bdauer Regarding the dashes, @tylerphillips55 has written an ever better regex that needs to be used. It's lying in utils, and right now the code is not using it.

**Comment by Mester** [comment]
Um I tried do as Anub suggested, to center the table. But lots of magical and weird things happened so I have no idea and will step back so I don't ruin things :P

**Pull request merged**
